#!/bin/bash

# This scripts creates all the links in the home directory

dots_dir=$HOME/dots
backup_dir=$(mktemp -d -p $dots_dir)
if [[ $? != 0 ]] ; then
   echo "error: Failed to create backup directory in $dots_dir"
fi
echo "Created backup directory $backup_dir" 

link_file() {
   # Utility function to link file
   # If file exists it is backed up in the tmp directory
   # First argument is the file
   curdir=$(pwd)
   cd $HOME
   if [[ -n "$1" ]] ; then
      if [[ -e "$1" ]] ; then
         mv $1 $backup_dir/.
      fi
      file_name=$(basename $1)
      echo "ln -s $dots_dir/$1 $file_name"
   fi
   cd $curdir
}


files=("bash/.bashrc" "bash/.inputrc" "bash/.bash_aliases")


for afile in "${files[@]}" 
do
   read -p "Link $afile?" yn
   case $yn in
      [Yy]* ) echo "linking $afile";
              link_file $afile;; 
          * ) echo "skipping $afile";;
   esac
done

